config/routes.rb
Rails.application.routes.draw do
  get 'scripts/:app/:file', :to => 'scripts#show'
  resources :manifests
  get 'packages/search'
  get 'packages/detail'
  root :to => 'manifests#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/backend.rb
require'cgi'
require 'json'
require 'net/http'
require 'uri'

class SomeBadException < StandardError; end
# curl 'http://127.0.0.1:5984/npmjs/_design/search/_search/packagename?limit=10&q=default%3Aoffice-ui-fabric*' \
#   -H 'Connection: keep-alive' \
#   -H 'Pragma: no-cache' \
#   -H 'Cache-Control: no-cache' \
#   -H 'accept: application/json' \
#   -H 'sec-ch-ua-mobile: ?0' \
#   -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36' \
#   -H 'sec-ch-ua: "Google Chrome";v="87", " Not;A Brand";v="99", "Chromium";v="87"' \
#   -H 'Content-Type: application/json' \
#   -H 'Sec-Fetch-Site: same-origin' \
#   -H 'Sec-Fetch-Mode: cors' \
#   -H 'Sec-Fetch-Dest: empty' \
#   -H 'Referer: http://127.0.0.1:5984/_utils/' \
#   -H 'Accept-Language: en-US,en;q=0.9' \
#   -H 'Cookie: hblid=KijlRWDikE0XmNgz3m39N0Wo4fFr4bBA; olfsk=olfsk8550109738064684; AuthSession=YWRtaW46NUZGNEI3NTk6Ash4hPvYSo0izlw1B-4w5ftb3XM' \
#   --compressed

class Backend
  def initialize
    @base = URI("http://#{ENV['COUCH_SERVER'] || "127.0.0.1"}:5984/npmjs")
  end

  def search query
    params = { :limit => 10, :q => "default:#{query}*" }
    search_uri = @base.clone
    search_uri.path += "/_design/search/_search/packagename"
    search_uri.query = URI.encode_www_form(params)


    http = Net::HTTP.new(search_uri.host, search_uri.port)

    req = Net::HTTP::Get.new(search_uri)
    req.basic_auth 'admin', 'password'

    res = http.request(req)

    if res.is_a?(Net::HTTPSuccess)
      transform_search_results JSON.parse(res.body)
    else
      raise SomeBadException.new
    end
  end

  def detail package_name
    fetch_uri = @base.clone
    fetch_uri.path += "/" + CGI.escape(package_name)
    http = Net::HTTP.new(fetch_uri.host, fetch_uri.port)
    req = Net::HTTP::Get.new(fetch_uri)
    req.basic_auth 'admin', 'password'
    res = http.request(req)
    if res.is_a?(Net::HTTPSuccess)
      JSON.parse(res.body)
    else
      raise SomeBadException.new
    end
  end

  def transform_search_results hits
    { :total => hits['total_rows'],
      :packages => hits['rows'].map { |r| r['fields']['default'] } }
  end
end

app/models/manifest.rb
class Manifest < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/manifests_controller.rb
class ManifestsController < ApplicationController
  before_action :set_manifest, only: [:show, :edit, :update, :destroy]

  # GET /manifests
  def index
    @manifests = Manifest.all
  end

  # GET /manifests/1
  def show
  end

  # GET /manifests/new
  def new
    @manifest = Manifest.new
  end

  # GET /manifests/1/edit
  def edit
  end

  # POST /manifests
  def create
    @manifest = Manifest.new(manifest_params)

    if @manifest.save
      redirect_to @manifest, notice: 'Manifest was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /manifests/1
  def update
    if @manifest.update(manifest_params)
      redirect_to @manifest, notice: 'Manifest was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /manifests/1
  def destroy
    @manifest.destroy
    redirect_to manifests_url, notice: 'Manifest was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_manifest
      @manifest = Manifest.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def manifest_params
      params.require(:manifest).permit(:name, :react_version, :react_dom_version, :fluent_version)
    end
end

app/controllers/packages_controller.rb
class PackagesController < ApplicationController
  def search
    b = Backend.new
    result = b.search(params[:q])
    render :json => result
  end

  def detail
    b = Backend.new
    result = b.detail(params[:q])
    render :json => result
  end
end

app/controllers/scripts_controller.rb
class ScriptsController < ApplicationController
  protect_from_forgery :except => :show
  def show
    app = Manifest.find_by(:name => params[:app])
    dir = nil
    version = nil
    if params[:file] == 'vendors-node_modules_react_index_js'
      dir = 'react'
      version = app.react_version
    elsif params[:file] == 'vendors-node_modules_react-dom_index_js'
      dir = 'react_dom'
      version = app.react_dom_version
    elsif params[:file] == 'vendors-node_modules_fluentui_react_lib_index_js'
      dir = 'fluentui_react'
      version = app.fluent_version
    end
    file = File.join(File.dirname(__FILE__), '..', '..', 'lib', 'assets', dir, version, 'file')
    send_file file, type: 'application/javascript', disposition: 'inline'
  end
end

app/helpers/manifests_helper.rb
module ManifestsHelper
end

app/helpers/scripts_helper.rb
module ScriptsHelper
end

app/views/manifests/_form.html.erb
<%= form_with(model: manifest) do |form| %>
  <% if manifest.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(manifest.errors.count, "error") %> prohibited this manifest from being saved:</h2>

      <ul>
        <% manifest.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :react_version %>
    <%= form.text_field :react_version %>

    <p>Valid values are: <pre>16.14.0</pre>, <pre>17.0.1</pre></p>
  </div>

  <div class="field">
    <%= form.label :react_dom_version %>
    <%= form.text_field :react_dom_version %>

    <p>Valid values are: <pre>16.14.0</pre>, <pre>17.0.1</pre></p>
  </div>

  <div class="field">
    <%= form.label :fluent_version %>
    <%= form.text_field :fluent_version %>

    <p>Valid values are: <pre>7.155.3</pre>, <pre>8.0.0-beta.33</pre></p>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/manifests/edit.html.erb
<h1>Editing Manifest</h1>

<%= render 'form', manifest: @manifest %>

<%= link_to 'Show', @manifest %> |
<%= link_to 'Back', manifests_path %>

app/views/manifests/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Manifests</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>React version</th>
      <th>React dom version</th>
      <th>Fluent version</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @manifests.each do |manifest| %>
      <tr>
        <td><%= manifest.name %></td>
        <td><%= manifest.react_version %></td>
        <td><%= manifest.react_dom_version %></td>
        <td><%= manifest.fluent_version %></td>
        <td><%= link_to 'Show', manifest %></td>
        <td><%= link_to 'Edit', edit_manifest_path(manifest) %></td>
        <td><%= link_to 'Destroy', manifest, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Manifest', new_manifest_path %>

app/views/manifests/new.html.erb
<h1>New Manifest</h1>

<%= render 'form', manifest: @manifest %>

<%= link_to 'Back', manifests_path %>

app/views/manifests/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @manifest.name %>
</p>

<p>
  <strong>React version:</strong>
  <%= @manifest.react_version %>
</p>

<p>
  <strong>React dom version:</strong>
  <%= @manifest.react_dom_version %>
</p>

<p>
  <strong>Fluent version:</strong>
  <%= @manifest.fluent_version %>
</p>

<%= link_to 'Edit', edit_manifest_path(@manifest) %> |
<%= link_to 'Back', manifests_path %>

app/views/scripts/show.html.erb
<h1>Scripts#show</h1>
<p>Find me in app/views/scripts/show.html.erb</p>